name: 'crdn'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - vega_datasets
  - altair_saver
  - selenium<4.3.0
  - pandas<1.5
  - pip
  - pip:
    - pandas_profiling
    - ipywidgets